[package]
name = "day05"
version = "0.1.0"
authors = ["Christian Grasso <chris54721@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"